---
- block:

  - name: stop supervisor
    service:
      name: supervisor
      state: stopped

  - name: Asegurar que el grupo {{ group }} exista
    group:
      name: "{{ group }}"
      state: present

  - name: Agregar el usuario {{ user }} con el grupo especifico {{ group }}
    user:
      name: "{{ user }}"
      uid: 1040
      group: "{{ group }}"
      home: "{{ home }}"
      system: yes
      shell: /bin/bash

  - name: Valida carpetas de necesarias para el projecto
    stat:
      path: "{{ item }}"
    register: folder_stats
    with_items:
      - "{{ home }}/{{ project_name }}"
      - /var/log/airflow
      - "/var/log/{{ project_name }}"
      - /etc/nginx/sites-enabled
      - /etc/nginx/sites-available
      - /usr/local/airflow

  - name: Crear carpetas de necesarias para el projecto
    file:
      path: "{{ item.item }}"
      state: directory
    when: item.stat.exists == false
    with_items:
      - "{{folder_stats.results}}"

  - name: Da permisos al directorio {{ home }}
    file:
      path: "{{ home }}"
      recurse: yes
      owner: "{{ user }}"
      group: "{{ group }}"

  - name: Valida que el directorio del proyecto no esta vacio
    find:
      paths: "{{ home }}/{{ project_name }}"
    register: home_proyect

  - name: Mover directorio si no existe el volumen
    copy:
      src: /tmp/project
      dest: "{{ home }}"
      force: no
    when: home_proyect.matched == 0

  - name: Creando archivo de log para el projecto
    file:
      path: "/var/log/{{ project_name }}/{{ project_name }}.log"
      state: touch
      mode: 0766

  - name: Instalar requerimientos de {{ project_name }}
    pip:
      requirements: /tmp/requirements.txt
      virtualenv: /opt/venv
      virtualenv_python: python3
      # executable: pip3
      extra_args: --no-cache-dir

- block:
  - name: Airflow | Update configuration (airflow.cfg)
    template:
      src: airflow.cfg.j2
      dest: "/usr/local/airflow/airflow.cfg"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644

  - name: Preparando los disparadores de la aplicacion
    template:
      src: "{{ item }}.j2"
      dest: "/usr/local/bin/{{ item }}"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0755
    with_items:
      - project_start
      - project_websocket_start
      - airflow-flower
      - airflow-scheduler
      - airflow-server
      - airflow-queue
      - create-admin
      - entrypoint
      - log-project
      - log-supervisor
      - log-websocket


  - name: Inicializa variable programas
    set_fact:
      queues: "{{ lookup('template', 'queue_vars.yml.j2') | from_yaml }}"

  - name: Preparando los disparadores para las colas
    template:
      src: airflow-queue.j2
      dest: "/usr/local/bin/airflow-queue-{{ item }}"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0755
    with_items:
      - "{{ queues }}"

  - name: Supervisor app | Update configuration (app.supervisor.conf)
    template:
      src: project.supervisor.conf.j2
      dest: "/etc/supervisor/conf.d/programs.conf"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644

  - name: Supervisor | crea las configuraciones
    command: echo_supervisord_conf > /etc/supervisord.conf
  
  - name: Supervisor | Update configuration (supervisor.conf)
    template:
      src: supervisord.conf.j2
      dest: "/etc/supervisord.conf"
      owner: root
      group: root
      mode: 0644

  - name: Nginx | Update configuration (nginx.conf)
    template:
      src: nginx.conf.j2
      dest: "/etc/nginx/sites-available/{{ project_name }}.conf"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0655

  - name: Nginx timeout | Update configuration (timeout.conf)
    template:
      src: timeout.conf.j2
      dest: "/etc/nginx/conf.d/timeout.conf"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644

  - name: Create symbolic link NGINX
    file:
      src: "/etc/nginx/sites-available/{{ project_name }}.conf"
      dest: "{{ item }}"
      state: link
    with_items:
      - "/etc/nginx/sites-enabled/{{ project_name }}.conf"
      - "/etc/nginx/conf.d/{{ project_name }}.conf"

  - name: Create symbolic link airflow dags
    file:
      src: "{{ home }}/{{ project_name }}/airflow/dags"
      dest: "/usr/local/airflow/dags"
      force: yes
      state: link

  - name: Remove Nginx file default file
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent
...